### ISSUE TITLE
Routing on SURF-WAVE is suboptimal

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#135]
**Describe the bug**
Swaps on WAVE->SURF are trying to route through WETH-WAVE, creating deeply suboptimal swaps

**To Reproduce**
1. Go to app.honeyswap.org
2. Set the trading pair to WAVE and SURF

**Expected behavior**
Routing through WAFE-SURF pair

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60b150d0aa64fc7a662399c6/e76649fb-ca38-4ac6-b150-262d25708e56)
![image.png](https://images.zenhubusercontent.com/60b150d0aa64fc7a662399c6/be99384a-a1b2-44d8-9bd3-fb815ca940fb)
![image.png](https://images.zenhubusercontent.com/60b150d0aa64fc7a662399c6/0aab2605-f17f-4139-8eac-7f5febc94d99)

**Comment by ceresbzns** [comment]
Let's add SURF-WAVE to list of front-end route base pairs

**Comment by mattreallycodes** [comment]
Can someone assign this to me please?

**Comment by ceresbzns** [comment]
It's yours to work. I'll assign in GitHub when I get the chance.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ceresbzns** [comment]
Hernando has some insight that should help.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by hernandoagf** [comment]
I found Honeyswap Router is using a list of tokens to use as "Intermediary pairs for trading", it probably just checks these tokens to construct the routes, and, since neither Surf nor Wave is in this list it's not finding any good route. A quick fix for this issue could be adding Surf and Wave to this list of tokens, however, we should figure out a better way to handle this, maybe by using the default token list if that doesn't make the routing slow.

Here's a screenshot for reference:
![image.png](https://images.zenhubusercontent.com/602dbcc7fca8f577efb767cd/ca6a5a65-3da4-42c7-b5ca-f565724a70da)

**Comment by mattreallycodes** [comment]
@hernandoagf Thank you for the insight. I will look at better ways to solve this.

**Comment by mattreallycodes** [comment]
@ceresbzns Can I please get access to the Github repo for this? I don't see this code when I do a search for it so I am guessing it's private?

**Comment by hernandoagf** [comment]
@mattreallycodes the screenshot is from the [Honeyswap-interface repo](https://github.com/1Hive/honeyswap-interface), specifically [this file](https://github.com/1Hive/honeyswap-interface/blob/master/src/constants/index.ts#L90). I think everyone has access to see that repo by default
