### ISSUE TITLE
HSF Farming Contract Equation

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#8]
Determine the equation used for HSF Token rewards

**Comment by Blazarius120** [comment]
-Time based multiplier or time lock?

**Comment by Philogy** [comment]
suggestion (pool share formula):
if no time lock: `pool_share = deposit_amount`
else if time locked: `pool_share = deposit_amount * lock_reward_factor * min(max_rewarded_time, lock_time)`

For the actual reward formula (how much to distribute / unit time) I'd suggest either a constant amount of tokens / unit_time or linearly decreasing amount.

**Comment by Philogy** [comment]
Math for a linear variant:
* Variables: formula slope `m`, total time over which to distribute tokens `te`, total tokens to be distributed `s`, amount per unit time to be distributed at the start `ds`, how much should be distributed at the end vs beginning `r` (0-1.0), current time `t`, amount to be distributed at certain time `f(t)`

`ds = (2 * s) / te / (r + 1)`
`m = ds * (r - 1) / te`
`f(t) = m * t + ds`

Integrating `f(t)` from `0` to `te` results in `s`. Integral is also easy to calculate since it's just a polynomial (`F(t) = 1/2 * m * t^2 + ds * t`).
